function so = putopt(win, config, trial)
%PUTOPT Places the options around the windows
%   Handles the pre-decision-making section of each trial
global state

if strcmp(state, 'before-admin')
    [A1, A2, B1, B2, prob, trialType] = ldtrialinfo(config.condition.mat1, trial);
elseif strcmp(state, 'after-admin')
    [A1, A2, B1, B2, prob, trialType] = ldtrialinfo(config.condition.mat2, trial);
end

coord = config.graphics.coord;
penWidth = config.graphics.option_pw;
r = config.graphics.option_r;

if strcmp(trname(trialType), "info: rr")
    upper_options = [B1, B2, B1, B2];
    so = 0;
elseif strcmp(trname(trialType), "info: ss")
    upper_options = [A1, A2, A1, A2];
    so = 0;
elseif strcmp(trname(trialType), "info: rs")
    if(randi([0, 1]) == 0)
        upper_options = [A1, A2, B1, B2];
        so = 1;
    else
        upper_options = [B1, B2, A1, A2];
        so = 2;
    end
elseif strcmp(trname(trialType), "solo")
    so = 0;
end

Screen('DrawLine', win, 255, coord.div.start(1), coord.div.start(2), ...
        coord.div.finish(1), coord.div.finish(2), penWidth);
drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', [A1, A2])
drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', [B1, B2])

if strcmp(trname(trialType), "solo")
    drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
        'OptionTitle', 8211, ...
        'FrameColor', 255)
    drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
        'OptionTitle', 8211, ...
        'FrameColor', 255)
    drawoption(win, coord.option_c(3,:), r, ...
        'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
        'FrameColor', 255, ...
        'NullSymbol', 63)
    Screen('Flip', win);
    
    WaitSecs(config.time.presentation_solo);
    
    Screen('DrawLine', win, 255, coord.div.start(1), coord.div.start(2), ...
        coord.div.finish(1), coord.div.finish(2), penWidth);
    drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
        'OptionTitle', 8211, ...
        'FrameColor', 255)
    drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
        'OptionTitle', 8211, ...
        'FrameColor', 255)
    drawoption(win, coord.option_c(3,:), r, ...
        'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
        'FrameColor', [255, 0, 0], ...
        'NullSymbol', 63)
    drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', [A1, A2])
    drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', [B1, B2])
    Screen('Flip', win);
else
%     Screen('DrawLine', win, 255, ...
%         coord.div.start(1), coord.div.start(2), coord.div.finish(1), coord.div.finish(2), penWidth);
%     drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
%         'OptionTitle', config.graphics.unicode.person_1_choice, ...
%         'FrameColor', [255, 0, 0])
%     drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
%         'OptionTitle', config.graphics.unicode.person_2_choice)
%     drawoption(win, coord.option_c(3,:), r, ...
%         'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
%         'NullSymbol', 63)
%     drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [A1, A2])
%     drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [B1, B2])
%     Screen('Flip', win);
    
%     WaitSecs(config.time.reveal_base + rand()*config.time.reveal_max_jitter);
%     
%     Screen('DrawLine', win, 255, ...
%         coord.div.start(1), coord.div.start(2), coord.div.finish(1), coord.div.finish(2), penWidth);
%     drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
%         'OptionTitle', config.graphics.unicode.person_1_choice)
%     drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
%         'OptionTitle', config.graphics.unicode.person_2_choice, ...
%         'FrameColor', [255, 0, 0])
%     drawoption(win, coord.option_c(3,:), r, ...
%         'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
%         'NullSymbol', 63)
%     drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [A1, A2])
%     drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [B1, B2])
%     Screen('Flip', win);
    
%     WaitSecs(config.time.reveal_base + rand()*config.time.reveal_max_jitter);
    
%     Screen('DrawLine', win, 255, ...
%         coord.div.start(1), coord.div.start(2), coord.div.finish(1), coord.div.finish(2), penWidth);
    drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', upper_options(1:2), ...
        'OptionTitle', config.graphics.unicode.person_1_choice)
    drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', upper_options(3:4), ...
        'OptionTitle', config.graphics.unicode.person_2_choice)
    drawoption(win, coord.option_c(3,:), r, ...
        'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
        'NullSymbol', 63, ...
        'FrameColor', 255)
%     drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [A1, A2])
%     drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
%         'Probability', prob', 'Values', [B1, B2])
    Screen('Flip', win);
    
    WaitSecs(config.time.thinking_duration);
    
    Screen('DrawLine', win, 255, ...
        coord.div.start(1), coord.div.start(2), coord.div.finish(1), coord.div.finish(2), penWidth);
    drawoption(win, coord.option_c(1,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', upper_options(1:2), ...
        'OptionTitle', config.graphics.unicode.person_1_choice)
    drawoption(win, coord.option_c(2,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', ...
        'Values', upper_options(3:4), ...
        'OptionTitle', config.graphics.unicode.person_2_choice)
    drawoption(win, coord.option_c(3,:), r, ...
        'PenWidth', penWidth, 'OptionTitle', config.graphics.unicode.your_choice, ...
        'NullSymbol', 63, ...
        'FrameColor', [255, 0, 0])
    drawoption(win, coord.option_c(4,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', 'Values', [A1, A2])
    drawoption(win, coord.option_c(5,:), r, 'PenWidth', penWidth, ...
        'Probability', prob', 'Values', [B1, B2])
    Screen('Flip', win);
end

end

